version: '3.8'

services:
  pos-system:
    build: .
    container_name: pos-system
    restart: unless-stopped
    expose:
      - "5000"
    volumes:
      - /root/data/pos:/app/database
    environment:
      - TZ=Asia/Kuwait
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
